### ISSUE TITLE
PicoContainer not on classpath

### ISSUE THREAD

**Issue by AlecStrong** [JetBrains/gradle-grammar-kit-plugin#14]
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/picocontainer/ComponentAdapter
	at org.intellij.grammar.LightPsi$MyParsing.<init>(LightPsi.java:191)
	at org.intellij.grammar.LightPsi.<clinit>(LightPsi.java:93)
	at org.intellij.grammar.Main.main(Main.java:49)
Caused by: java.lang.ClassNotFoundException: org.picocontainer.ComponentAdapter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
```

happens when trying to generate the parser. Looks like theres a reference from here: https://github.com/JetBrains/Grammar-Kit/blob/master/src/org/intellij/grammar/LightPsi.java#L73

and the main grammar kit project just has it included as a jar in the libs/ directory.

**Comment by AlecStrong** [comment]
I _think_ this would be resolved if grammar-kit targeted 2018?

**Comment by AlecStrong** [comment]
and nevermind I didn't realize the names of jars changed in intellij with 2018.3 so I just needed to load them differently. My bad! The PR linked above includes the fix I had to do locally if anyone else runs into this
