### ISSUE TITLE
ClassCastException: MockApplication cannot be cast to ApplicationEx

### ISSUE THREAD

**Issue by carymrobbins** [JetBrains/gradle-grammar-kit-plugin#21]
Project/Commit: https://github.com/carymrobbins/intellij-haskforce/commit/183363f23387236ca150097b102afddabd27d487

When attempting to invoke grammar-kit via my `generateHaskellParser` task, I get the following exception and stack trace. Issue https://github.com/JetBrains/gradle-grammar-kit-plugin/issues/17 sounds somewhat related, but I'm not entirely sure.

```
java.lang.ClassCastException: com.intellij.mock.MockApplication cannot be cast to com.intellij.openapi.application.ex.ApplicationEx                                                                                                      
        at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:59)
        at com.intellij.psi.impl.search.PsiSearchHelperImpl.bulkProcessElementsWithWord(PsiSearchHelperImpl.java:200)                                                                                                                    
        at com.intellij.psi.impl.search.PsiSearchHelperImpl.processSingleRequest(PsiSearchHelperImpl.java:938)
        at com.intellij.psi.impl.search.PsiSearchHelperImpl.processRequests(PsiSearchHelperImpl.java:604)
        at com.intellij.psi.search.SearchRequestQuery.processResults(SearchRequestQuery.java:24)
        at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:91)
        at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:114)
        at com.intellij.util.MergeQuery.processResults(MergeQuery.java:26)
        at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:91)
        at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:114)
        at com.intellij.util.UniqueResultsQuery.processResults(UniqueResultsQuery.java:40)
        at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:91)
        at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:83)
        at org.intellij.grammar.generator.ParserGeneratorUtil.isUsedAsArgument(ParserGeneratorUtil.java:757)
        at org.intellij.grammar.generator.ParserGenerator.generateNode(ParserGenerator.java:850)
        at org.intellij.grammar.generator.ParserGenerator.generateParser(ParserGenerator.java:571)
        at org.intellij.grammar.generator.ParserGenerator.generateParser(ParserGenerator.java:524)
        at org.intellij.grammar.generator.ParserGenerator.generate(ParserGenerator.java:372)
        at org.intellij.grammar.Main.main(Main.java:85)
```

**Comment by gregsh** [comment]
Shall be fixed long ago.
