### ISSUE TITLE
Infinite analysis in BNF file in IDEA

### ISSUE THREAD

**Issue by vlad20012** [JetBrains/gradle-grammar-kit-plugin#28]
If I open the Rust grammar in IDEA with Grammar Kit plugin, the analysis never completes and one thread uses 100% of the core (thread dump attached).

Grammar Kit plugin version: 2019.3
BNF file: https://github.com/intellij-rust/intellij-rust/blob/master/src/main/grammars/RustParser.bnf

IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Build #IU-193.6494.35, built on February 11, 2020
Licensed to JetBrains Team

Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-40-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: ide.tooltip.initialDelay=400
Non-Bundled Plugins: Key Promoter X, PsiViewer, com.intellij.sisyphus, org.intellij.scala, org.jetbrains.kotlin, org.toml.lang, tanvd.grazi, org.rust.lang, com.jetbrains.edu, com.jetbrains.hackathon.indices.viewer, com.jetbrains.intellij.api.watcher, org.jetbrains.idea.grammar

<details>
  <summary>Thread dump</summary>
 
  ```
"JobScheduler FJ pool 5/3" #337 daemon prio=4 os_prio=0 cpu=41941,88ms elapsed=1527,89s tid=0x00007fbdf934b800 nid=0x8df runnable  [0x00007fbd927f5000]
   java.lang.Thread.State: RUNNABLE
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$ASTTreeGuide.getParent(RecursiveTreeElementWalkingVisitor.java:53)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$ASTTreeGuide.getParent(RecursiveTreeElementWalkingVisitor.java:35)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:67)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitNode(RecursiveTreeElementWalkingVisitor.java:86)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitComposite(RecursiveTreeElementWalkingVisitor.java:81)
	at com.intellij.psi.impl.source.tree.AstBufferUtil$BufferVisitor.visitComposite(AstBufferUtil.java:115)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:130)
	at com.intellij.psi.impl.source.tree.AstBufferUtil.toBuffer(AstBufferUtil.java:40)
	at com.intellij.psi.impl.source.tree.AstBufferUtil.toBuffer(AstBufferUtil.java:35)
	at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:244)
	at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:225)
	at org.intellij.grammar.generator.ParserGeneratorUtil.getTokenName(ParserGeneratorUtil.java:633)
	at org.intellij.grammar.generator.ParserGeneratorUtil.getTokenNames(ParserGeneratorUtil.java:621)
	at org.intellij.grammar.generator.ParserGeneratorUtil.getTokenNames(ParserGeneratorUtil.java:614)
	at org.intellij.grammar.generator.ParserGeneratorUtil.isTokenSequence(ParserGeneratorUtil.java:649)
	at org.intellij.grammar.psi.impl.GrammarUtil.processExpressionNames(GrammarUtil.java:143)
	at org.intellij.grammar.psi.impl.GrammarUtil.processExpressionNames(GrammarUtil.java:145)
	at org.intellij.grammar.psi.impl.GrammarUtil.processPinnedExpressions(GrammarUtil.java:155)
	at org.intellij.grammar.psi.impl.GrammarUtil.processPinnedExpressions(GrammarUtil.java:151)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcSequenceFirstInner(BnfFirstNextAnalyzer.java:183)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcNextInner(BnfFirstNextAnalyzer.java:129)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:318)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcSequenceFirstInner(BnfFirstNextAnalyzer.java:198)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcNextInner(BnfFirstNextAnalyzer.java:129)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:318)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:252)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:243)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcSequenceFirstInner(BnfFirstNextAnalyzer.java:198)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcNextInner(BnfFirstNextAnalyzer.java:129)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:318)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:252)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:243)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcSequenceFirstInner(BnfFirstNextAnalyzer.java:198)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcNextInner(BnfFirstNextAnalyzer.java:129)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:318)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcSequenceFirstInner(BnfFirstNextAnalyzer.java:198)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcNextInner(BnfFirstNextAnalyzer.java:129)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:318)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:252)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:243)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcSequenceFirstInner(BnfFirstNextAnalyzer.java:198)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcNextInner(BnfFirstNextAnalyzer.java:129)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:318)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcSequenceFirstInner(BnfFirstNextAnalyzer.java:198)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcNextInner(BnfFirstNextAnalyzer.java:129)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:318)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:252)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:243)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcSequenceFirstInner(BnfFirstNextAnalyzer.java:198)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcNextInner(BnfFirstNextAnalyzer.java:129)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:318)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:252)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:243)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcSequenceFirstInner(BnfFirstNextAnalyzer.java:198)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcNextInner(BnfFirstNextAnalyzer.java:129)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:318)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcSequenceFirstInner(BnfFirstNextAnalyzer.java:198)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcNextInner(BnfFirstNextAnalyzer.java:129)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:318)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:252)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:243)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcSequenceFirstInner(BnfFirstNextAnalyzer.java:198)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcNextInner(BnfFirstNextAnalyzer.java:129)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:318)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcSequenceFirstInner(BnfFirstNextAnalyzer.java:198)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcNextInner(BnfFirstNextAnalyzer.java:129)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:318)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcFirstInner(BnfFirstNextAnalyzer.java:207)
	at org.intellij.grammar.inspection.BnfUnreachableChoiceBranchInspection.checkChoice(BnfUnreachableChoiceBranchInspection.java:60)
	at org.intellij.grammar.inspection.BnfUnreachableChoiceBranchInspection.access$000(BnfUnreachableChoiceBranchInspection.java:40)
	at org.intellij.grammar.inspection.BnfUnreachableChoiceBranchInspection$1.visitChoice(BnfUnreachableChoiceBranchInspection.java:47)
	at org.intellij.grammar.inspection.BnfUnreachableChoiceBranchInspection$1.visitChoice(BnfUnreachableChoiceBranchInspection.java:44)
	at org.intellij.grammar.psi.impl.BnfChoiceImpl.accept(BnfChoiceImpl.java:35)
	at org.intellij.grammar.psi.impl.BnfChoiceImpl.accept(BnfChoiceImpl.java:39)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:77)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$6(LocalInspectionsPass.java:332)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$$Lambda$4072/0x0000000102c01440.run(Unknown Source)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:167)
	at com.intellij.util.AstLoadingFilter$$Lambda$2248/0x0000000101c58440.compute(Unknown Source)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:125)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:114)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:109)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$7(LocalInspectionsPass.java:331)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$$Lambda$4071/0x0000000102c01040.process(Unknown Source)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:148)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:227)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:155)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:227)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:155)
	at com.intellij.concurrency.ApplierCompleter$$Lambda$4012/0x0000000102b5a440.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.concurrency.ApplierCompleter$$Lambda$4013/0x0000000102b59840.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.concurrency.ApplierCompleter$$Lambda$4011/0x0000000102b5a040.run(Unknown Source)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:157)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(java.base@11.0.5/CountedCompleter.java:746)
	at java.util.concurrent.ForkJoinTask.doExec(java.base@11.0.5/ForkJoinTask.java:290)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@11.0.5/ForkJoinPool.java:1020)
	at java.util.concurrent.ForkJoinPool.scan(java.base@11.0.5/ForkJoinPool.java:1656)
	at java.util.concurrent.ForkJoinPool.runWorker(java.base@11.0.5/ForkJoinPool.java:1594)
	at java.util.concurrent.ForkJoinWorkerThread.run(java.base@11.0.5/ForkJoinWorkerThread.java:177)
  ```
</details>

**Comment by gregsh** [comment]
That should have been reported in [Grammar Kit](https://github.com/JetBrains/Grammar-Kit/issues) tracker.
