### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/Hash$Strategy while generating parser

### ISSUE THREAD

**Issue by BrianPin** [JetBrains/gradle-grammar-kit-plugin#31]
Hi 

I happened to see this build failure when I switch to use new JetBrain sdk release 2020.2, (before it was fine).

it failed to build because the exception:

```
> Task :pegasusplugin:generatePdlParser FAILED
Exception in thread "main" java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/Hash$Strategy
        at com.intellij.core.CoreFileTypeRegistry.<init>(CoreFileTypeRegistry.java:23)
        at com.intellij.core.CoreApplicationEnvironment.<init>(CoreApplicationEnvironment.java:83)
        at com.intellij.core.CoreApplicationEnvironment.<init>(CoreApplicationEnvironment.java:74)
        at org.intellij.grammar.LightPsi$MyParsing.<init>(LightPsi.java:166)
        at org.intellij.grammar.LightPsi.<clinit>(LightPsi.java:65)
        at org.intellij.grammar.Main.main(Main.java:49)
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.Hash$Strategy
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 6 more
```

After I switch back to use 2020.1, it builds fine.

How should I solve this problem? Will it be necessary to have changes from JetBrain ?

This is happening while generate parse gradle task is running

**Comment by BrianPin** [comment]
I tried switching between grammarkit gradle plugin version 2019.3 and 2020.1 both are not capable of solving this problem.

**Comment by BrianPin** [comment]
Can anyone help on this issue?

**Comment by tsalzinger** [comment]
@BrianPin encountered the same issue but 2020.2.1 resolved exactly this issue - see commit https://github.com/JetBrains/gradle-grammar-kit-plugin/commit/de2bd41d79d0825b75bd43b2ea2f239b5aaccf0e
